steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['composer', 'environments', 'update', 'example-environment', '--update-pypi-packages-from-file', 'composer/requirements-composer.txt', '--location', 'us-central1']
timeout: 3600s # set timeout to 1h. It would be unusual for composer env to take 1h to update
